# Generated by Django 5.2.17 on 2026-08-18 22:42

import apps.accounts.validators
import apps.core.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', apps.core.text.NFCCharField(help_text='Minúsculas, números, ponto, hífen e sublinhado. Acentos aceitos.', max_length=30, unique=True, validators=[apps.accounts.validators.validate_username], verbose_name='nome de usuário')),
                ('username_skeleton', models.CharField(editable=False, max_length=30, unique=True)),
                ('display_name', apps.core.text.NFCCharField(max_length=60, validators=[apps.accounts.validators.validate_display_name], verbose_name='nome exibido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('bio', apps.core.text.NFCTextField(blank=True, max_length=2000, verbose_name='apresentação')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatares/', verbose_name='avatar')),
                ('trust_level', models.PositiveSmallIntegerField(choices=[(0, 'Novo'), (1, 'Básico'), (2, 'Membro'), (3, 'Regular'), (4, 'Moderador')], default=0, verbose_name='nível de confiança')),
                ('post_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='posts')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='acessa o admin')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='criado em')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='visto por último')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'ordering': ['username'],
            },
        ),
    ]
