# Generated by Django 5.2.17 on 2026-08-18 22:42

import apps.core.text
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcode', models.SlugField(unique=True, verbose_name='código')),
                ('character', models.CharField(blank=True, max_length=8, verbose_name='caractere')),
                ('image', models.ImageField(blank=True, null=True, upload_to='emojis/', verbose_name='imagem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('position', models.IntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'emoji',
                'verbose_name_plural': 'emojis',
                'ordering': ['position', 'shortcode'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', apps.core.text.NFCCharField(max_length=100, verbose_name='nome')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('description', apps.core.text.NFCTextField(blank=True, verbose_name='descrição')),
                ('color', models.CharField(default='#8B6F47', max_length=7, verbose_name='cor')),
                ('position', models.IntegerField(default=0, verbose_name='ordem')),
                ('is_locked', models.BooleanField(default=False, help_text='Apenas moderadores publicam.', verbose_name='trancada')),
                ('topic_count', models.PositiveIntegerField(default=0, editable=False)),
                ('post_count', models.PositiveIntegerField(default=0, editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='forum.category', verbose_name='categoria mãe')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='removido em')),
                ('position', models.PositiveIntegerField(editable=False, verbose_name='número no tópico')),
                ('body_md', apps.core.text.NFCTextField(verbose_name='texto')),
                ('body_html', models.TextField(blank=True, editable=False)),
                ('html_version', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='editado em')),
                ('edit_count', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='removido por')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='forum.post', verbose_name='em resposta a')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='PostRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('body_md', apps.core.text.NFCTextField(verbose_name='texto anterior')),
                ('edit_reason', apps.core.text.NFCCharField(blank=True, max_length=200, verbose_name='motivo')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='forum.post')),
            ],
            options={
                'verbose_name': 'revisão',
                'verbose_name_plural': 'revisões',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='removido em')),
                ('title', apps.core.text.NFCCharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(max_length=220, verbose_name='slug')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='fixado')),
                ('is_locked', models.BooleanField(default=False, verbose_name='trancado')),
                ('post_count', models.PositiveIntegerField(default=0, editable=False)),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('last_post_at', models.DateTimeField(db_index=True, null=True, verbose_name='último post em')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='forum.category', verbose_name='categoria')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='removido por')),
            ],
            options={
                'verbose_name': 'tópico',
                'verbose_name_plural': 'tópicos',
                'ordering': ['-is_pinned', '-last_post_at'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.topic', verbose_name='tópico'),
        ),
        migrations.CreateModel(
            name='PostLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('link_type', models.CharField(choices=[('quote', 'Citação'), ('reference', 'Referência'), ('mention', 'Menção'), ('crosspost', 'Post cruzado')], default='reference', max_length=20)),
                ('source_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_out', to='forum.post')),
                ('target_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_in', to='forum.post')),
            ],
            options={
                'verbose_name': 'vínculo entre posts',
                'verbose_name_plural': 'vínculos entre posts',
                'indexes': [models.Index(fields=['target_post'], name='postlink_alvo_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_post', 'target_post', 'link_type'), name='vinculo_unico')],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('emoji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='forum.emoji')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='forum.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reação',
                'verbose_name_plural': 'reações',
                'constraints': [models.UniqueConstraint(fields=('post', 'user', 'emoji'), name='reacao_unica_por_usuario')],
            },
        ),
        migrations.CreateModel(
            name='ReactionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('emoji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='forum.emoji')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_counts', to='forum.post')),
            ],
            options={
                'verbose_name': 'contagem de reações',
                'verbose_name_plural': 'contagens de reações',
                'constraints': [models.UniqueConstraint(fields=('post', 'emoji'), name='contagem_unica_post_emoji')],
            },
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['category', '-is_pinned', '-last_post_at'], name='topic_listagem_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['topic', 'position'], name='post_topico_posicao_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='post_busca_idx'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('topic', 'position'), name='post_posicao_unica'),
        ),
    ]
